[project]
name = "transformers-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.5.1",
    "transformers>=4.48.0",
]
